### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xinghuang2050** [hxmhuang/GOMO#5]
I used openmpi-3.0.4 to compile OpenArray and GOMO on Ubuntu 18.04.3, OpenArray was installed successfully, while installation of GOMO failed at the last step with the following errro:

![A make error](https://user-images.githubusercontent.com/22727295/62910760-5a676800-bdb4-11e9-86bf-d3e9f2aa9b13.png)

Note:  I used the latest version of GOMO (commit 74b4c8198931acfcb555f31655571236584f47eb)

**Comment by wangdong1991** [comment]
![image](https://user-images.githubusercontent.com/32699863/62915054-91924500-bdc5-11e9-83d7-af75583d2163.png)
Change the position of “-lopenarray” will solve this problem.
